name: CI

on: [push, pull_request]

jobs:
  skip_check:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master

  CI:
    needs: skip_check
    if: ${{ needs.skip_check.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 8, 11, 17 ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
      - uses: DeLaGuardo/setup-clojure@3.5
        with:
          tools-deps: latest

      - name: Run CI checks
        run: clojure -Srepro -J-Dclojure.main.report=stderr -T:build ci
